### ISSUE TITLE
Rejects relation filter 'unknown'

### ISSUE THREAD

**Issue by davisjam** [CamFlow/camconfd#20]
I tried to set node filters and relation filters to filter all [vertices](https://github.com/CamFlow/camflow-dev/blob/master/docs/VERTICES.md) and [relations](https://github.com/CamFlow/camflow-dev/blob/master/docs/RELATIONS.md) in my `/etc/camconf.ini` file.

I then rebooted the machine and found that `camconfd` choked when parsing my configuration. It complained about the 'unknown' relation.

If `camconfd` won't accept the 'unknown' relation, why is it listed in the set of all relations?

On a related note, after I rebooted the VM again (without changing the `/etc/camconf.ini` file) it was unusable -- extremely laggy and burning CPU. Any idea why this might be the case? Is the default behavior on a bad config file "trace everything"?

**Comment by tfjmp** [comment]
> If camconfd won't accept the 'unknown' relation, why is it listed in the set of all relations?

It is the default value taken if nothing match when generating the provenance output. However, it indeed does not seem to work well with the configuration. I need to give a bit of though regarding what is the best way to handle it:
1) ignoring it and providing some warning message stating that this config input has no effect;
2) or trying to handle it (although `unknown` appearing in the graph is not supposed to occur, and a bug somewhere in the stack if/when it does).

> On a related note, after I rebooted the VM again (without changing the /etc/camconf.ini file) it was unusable -- extremely laggy and burning CPU. Any idea why this might be the case? Is the default behavior on a bad config file "trace everything"?

What workload are you running? I have tried to reproduce the issue (running a kernel compile + browsing on firefox + normal background task), but the machine seemed pretty responsive. I also ran `top` to check what may be going on, while `camflowd` spiked at 100% now and then, but it was relatively short bursts. Note that I tested on a dev machine, that have some significant changes to camflowd, that may affect the performance. I will investigate further once I understand your setting a bit better.

Could you also give me the output of the following:
```
camflow -s
cat /etc/camflow.ini
cat /etc/camflowd.ini
```

**Comment by davisjam** [comment]
1. Have buggy versions of CamFlow had `unknown` in the graph in the past, and/or is this likely when tracking additional flows? If so this might be a useful filter for developers. If 'unknown' should not happen in practice, then you could un-publish its existence.

2. I think I retract my complaint about performance. The laggy mouse behavior does not seem tied to the status of CamFlow. It is laggy after reboot and whether or not the camflow services are running. Other VMs I have run through VirtualBox on this machine have been well-behaved, so I wonder whether there is some VM configuration that is causing this. Curious.

**Comment by tfjmp** [comment]
This is very old, and we have changed the VM. The unknown label issue should also have been solved as the software as mature and how labelled are now managed.
